[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]] #   Include nativefs module
[patches.module]
source = 'nativefs.lua'
before = 'main.lua'
name = 'nativefs'

[[patches]] #   Patch Mod to main
[patches.copy]
target = "main.lua"
position = "append"
sources = ["mod.lua"]

[[patches]] #   Initialize Mod
[patches.pattern]
target = "game.lua"
pattern = "self:load_profile(G.SETTINGS.profile or 1)"
position = "after"
payload = "loadMod()"
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.SOUND_MANAGER.thread:start(1)"
position = "at"
payload = '''
self.SOUND_MANAGER = initSoundManager()
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.FUNCS.demo_survey = function(e)"
position = "before"
payload = '''
G.FUNCS.palombi_twitch = function(e)
  love.system.openURL( "https://www.twitch.tv/dompalombimusic" )
end
'''
match_indent = true
overwrite = false
